In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Churn_Modelling.csv')

In [3]:
columns_to_drop = ['RowNumber', 'CustomerId', 'Surname']
df = df.drop(columns_to_drop, axis=1)

In [4]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [5]:
df = pd.get_dummies(df, columns=['Geography', 'Gender'], drop_first=True)

In [6]:
X = df.drop('Exited', axis=1)
y = df['Exited']

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

In [8]:
X_train.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_Germany,Geography_Spain,Gender_Male
9254,686,32,6,0.00,2,1,1,179093.26,False,False,True
1561,632,42,4,119624.60,2,1,1,195978.86,True,False,True
1670,559,24,3,114739.92,1,1,0,85891.02,False,True,True
6087,561,27,9,135637.00,1,1,0,153080.40,False,False,False
6669,517,56,9,142147.32,1,0,0,39488.04,False,False,True

In [9]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

In [18]:
model = RandomForestClassifier(n_estimators=100, class_weight='balanced', random_state=42)
model.fit(X_train, y_train)

RandomForestClassifier(class_weight='balanced', random_state=42)

In [19]:
predictions = model.predict(X_test)

In [20]:
print("Model Accuracy:", accuracy_score(y_test, predictions))

Model Accuracy: 0.869

In [21]:
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       0.88      0.97      0.92      1607
           1       0.79      0.46      0.58       393

    accuracy                           0.87      2000
   macro avg       0.83      0.71      0.75      2000
weighted avg       0.86      0.87      0.85      2000

In [22]:
from imblearn.over_sampling import SMOTE
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

In [23]:
smote = SMOTE(random_state=42)

In [24]:
X_train_smote, y_train_smote = smote.fit_resample(X_train, y_train)

In [25]:
print("Old training target counts:\n", y_train.value_counts().to_string())

Old training target counts:
 Exited
0    6356
1    1644

In [26]:
print("\nNew SMOTE training target counts:\n", y_train_smote.value_counts().to_string())
print("-" * 40)

New SMOTE training target counts:
 Exited
0    6356
1    6356
----------------------------------------

In [27]:
final_model = RandomForestClassifier(n_estimators=100, random_state=42)
final_model.fit(X_train_smote, y_train_smote)

RandomForestClassifier(random_state=42)

In [28]:
final_predictions = final_model.predict(X_test)

In [29]:
print(classification_report(y_test, final_predictions))

              precision    recall  f1-score   support

           0       0.91      0.89      0.90      1607
           1       0.58      0.64      0.61       393

    accuracy                           0.84      2000
   macro avg       0.75      0.77      0.75      2000
weighted avg       0.85      0.84      0.84      2000